FROM --platform=$BUILDPLATFORM node:17.0.1-bullseye-slim as builder

RUN mkdir /usr/src/ginger
WORKDIR /usr/src/ginger

RUN npm install -g @angular/cli@14

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build --production



FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
COPY --from=builder /usr/src/ginger/dist/ginger /usr/share/nginx/html